development:
  dialect: postgres
  database: sfcir_development
  user: postgres
  password: postgres
  host: 172.17.0.2
  #host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@172.17.0.2:5432/sfcir_test?sslmode=disable"}}
  #url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/sfcir_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@172.17.0.2:5432/sfcir_production?sslmode=disable"}}
  #url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/sfcir_production?sslmode=disable"}}
